x=input('Введите номер четверти: ')
if x == '1':print('x=[0,+oo];y=[0,+oo]')
elif x == '2':print('x=[0,-oo];y=[0,+oo]')
elif x == '3':print('x=[0,-oo];y=[0,-oo]')
elif x == '4':print ('x=[0,+oo];y=[0,-oo]')